/* This file was generated by SableCC (http://www.sablecc.org/). */

package Compiler.SableCC.postfix.node;

import Compiler.SableCC.postfix.analysis.*;

@SuppressWarnings("nls")
public final class TVConnector extends Token
{
    public TVConnector()
    {
        super.setText("--");
    }

    public TVConnector(int line, int pos)
    {
        super.setText("--");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TVConnector(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTVConnector(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TVConnector text.");
    }
}
