/* This file was generated by SableCC (http://www.sablecc.org/). */

package Compiler.SableCC.postfix.node;

import Compiler.SableCC.postfix.analysis.*;

@SuppressWarnings("nls")
public final class TVertex extends Token
{
    public TVertex()
    {
        super.setText("Vertex");
    }

    public TVertex(int line, int pos)
    {
        super.setText("Vertex");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TVertex(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTVertex(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TVertex text.");
    }
}
