package Compiler.Parser;

/* Generated By:JavaCC: Do not edit this line. testParserTreeConstants.java Version 6.0_1 */

public interface testParserTreeConstants
{
  public int JJTSKIP_TO_FIRST_DCL = 0;
  public int JJTSKIP_TO_EOF = 1;
  public int JJTONE_LINE = 2;
  public int JJTPROG = 3;
  public int JJTVERTEX_EDGE_DCL = 4;
  public int JJTATTRIBUTE_DCL = 5;
  public int JJTMAIN = 6;
  public int JJTBLOCK = 7;
  public int JJTBLOCK_CONTENT = 8;
  public int JJTDCL = 9;
  public int JJTIDENTIFIER = 10;
  public int JJTINITIALIZATION = 11;
  public int JJTADT = 12;
  public int JJTGRAPH_TYPE = 13;
  public int JJTGRAPH_DCL = 14;
  public int JJTGRAPH_ELEMENTS = 15;
  public int JJTGRAPH_VERTEX_DCL = 16;
  public int JJTGRAPH_VERTEX_DCL1 = 17;
  public int JJTVERTEX_LIST = 18;
  public int JJTVERTEX_LIST_CONTINUOUS = 19;
  public int JJTWEIGHT = 20;
  public int JJTEXPR = 21;
  public int JJTA = 22;
  public int JJTAND_EXPR = 23;
  public int JJTB = 24;
  public int JJTEQUAL_EXPR = 25;
  public int JJTEQUAL_EXPR1 = 26;
  public int JJTREL_EXPR = 27;
  public int JJTREL_EXPR1 = 28;
  public int JJTARITH_EXPR = 29;
  public int JJTC = 30;
  public int JJTTERM = 31;
  public int JJTD = 32;
  public int JJTNEG_EXPR = 33;
  public int JJTATOMIC_EXPR = 34;
  public int JJTVALUE = 35;
  public int JJTMEMBER_FUNCTION_CALL = 36;
  public int JJTMEMBER_FUNCTION_CALL_TAIL = 37;
  public int JJTCONTINUOUS = 38;
  public int JJTACTUAL_PARAMETERS = 39;
  public int JJTACTUAL_PARAMETER_LIST = 40;
  public int JJTACTUAL_PARAMETER_LIST1 = 41;
  public int JJTSIMPLE_TYPES = 42;
  public int JJTCOLLECTION_TYPE = 43;
  public int JJTCOLLECTION_DCL = 44;
  public int JJTELEMENT_LIST = 45;
  public int JJTELEMENT_LIST1 = 46;
  public int JJTFUNCS_DCL = 47;
  public int JJTFUNC_DCL = 48;
  public int JJTRET = 49;
  public int JJTFORMAL_PARAMETERS = 50;
  public int JJTFORMAL_PARAMETER_LIST = 51;
  public int JJTFORMAL_PARAMETER_LIST1 = 52;
  public int JJTFORMAL_PARAMETER = 53;
  public int JJTTYPE = 54;
  public int JJTOBJECT_TYPES = 55;
  public int JJTGRAPH_ELEMENT_TYPES = 56;
  public int JJTSTMT = 57;
  public int JJTASSIGN_OR_FUNC = 58;
  public int JJTRETURN_STMT = 59;
  public int JJTRETURN_EXPR = 60;
  public int JJTASSIGNMENT = 61;
  public int JJTLOOP = 62;
  public int JJTWHILE_STATEMENT = 63;
  public int JJTFOR_STATEMENT = 64;
  public int JJTINTEGER_VALUE = 65;
  public int JJTFOREACH_STATEMENT = 66;
  public int JJTIF_STATEMENT = 67;
  public int JJTELSE_STATEMENT = 68;
  public int JJTEMPTY = 69;


  public String[] jjtNodeName = {
    "skip_to_first_dcl",
    "skip_to_EOF",
    "ONE_LINE",
    "PROG",
    "VERTEX_EDGE_DCL",
    "ATTRIBUTE_DCL",
    "MAIN",
    "BLOCK",
    "BLOCK_CONTENT",
    "DCL",
    "IDENTIFIER",
    "INITIALIZATION",
    "ADT",
    "GRAPH_TYPE",
    "GRAPH_DCL",
    "GRAPH_ELEMENTS",
    "GRAPH_VERTEX_DCL",
    "GRAPH_VERTEX_DCL1",
    "VERTEX_LIST",
    "VERTEX_LIST_CONTINUOUS",
    "WEIGHT",
    "EXPR",
    "A",
    "AND_EXPR",
    "B",
    "EQUAL_EXPR",
    "EQUAL_EXPR1",
    "REL_EXPR",
    "REL_EXPR1",
    "ARITH_EXPR",
    "C",
    "TERM",
    "D",
    "NEG_EXPR",
    "ATOMIC_EXPR",
    "VALUE",
    "MEMBER_FUNCTION_CALL",
    "MEMBER_FUNCTION_CALL_TAIL",
    "CONTINUOUS",
    "ACTUAL_PARAMETERS",
    "ACTUAL_PARAMETER_LIST",
    "ACTUAL_PARAMETER_LIST1",
    "SIMPLE_TYPES",
    "COLLECTION_TYPE",
    "COLLECTION_DCL",
    "ELEMENT_LIST",
    "ELEMENT_LIST1",
    "FUNCS_DCL",
    "FUNC_DCL",
    "RET",
    "FORMAL_PARAMETERS",
    "FORMAL_PARAMETER_LIST",
    "FORMAL_PARAMETER_LIST1",
    "FORMAL_PARAMETER",
    "TYPE",
    "OBJECT_TYPES",
    "GRAPH_ELEMENT_TYPES",
    "STMT",
    "ASSIGN_OR_FUNC",
    "RETURN_STMT",
    "RETURN_EXPR",
    "ASSIGNMENT",
    "LOOP",
    "WHILE_STATEMENT",
    "FOR_STATEMENT",
    "INTEGER_VALUE",
    "FOREACH_STATEMENT",
    "IF_STATEMENT",
    "ELSE_STATEMENT",
    "EMPTY",
  };
}
/* JavaCC - OriginalChecksum=547c93da650439145d1a8e4a94b82902 (do not edit this line) */
