/* Generated By:JavaCC: Do not edit this line. testParserTreeConstants.java Version 5.0 */
package Compiler.Parser;

public interface testParserTreeConstants
{
  public int JJTONE_LINE = 0;
  public int JJTPROG = 1;
  public int JJTMAIN = 2;
  public int JJTBLOCK = 3;
  public int JJTBLOCK_CONTENT = 4;
  public int JJTDCL = 5;
  public int JJTIDENTIFIER = 6;
  public int JJTINITIALIZATION = 7;
  public int JJTADT = 8;
  public int JJTGRAPH_TYPE = 9;
  public int JJTGRAPH_DCL = 10;
  public int JJTGRAPH_DCL1 = 11;
  public int JJTGRAPH_VERTEX_DCL = 12;
  public int JJTGRAPH_VERTEX_DCL1 = 13;
  public int JJTVERTEX_LIST = 14;
  public int JJTVERTEX_LIST1 = 15;
  public int JJTWEIGHT = 16;
  public int JJTEXPR = 17;
  public int JJTA = 18;
  public int JJTAND_EXPR = 19;
  public int JJTB = 20;
  public int JJTEQUAL_EXPR = 21;
  public int JJTEQUAL_EXPR1 = 22;
  public int JJTREL_EXPR = 23;
  public int JJTREL_EXPR1 = 24;
  public int JJTARITH_EXPR = 25;
  public int JJTC = 26;
  public int JJTTERM = 27;
  public int JJTD = 28;
  public int JJTNEG_EXPR = 29;
  public int JJTATOMIC_EXPR = 30;
  public int JJTVALUE = 31;
  public int JJTVALUE1 = 32;
  public int JJTFUNCTION_CALL1 = 33;
  public int JJTFUNCTION_CALL = 34;
  public int JJTACTUAL_PARAMETERS = 35;
  public int JJTACTUAL_PARAMETER_LIST = 36;
  public int JJTACTUAL_PARAMETER_LIST1 = 37;
  public int JJTSIMPLE_TYPES = 38;
  public int JJTCOLLECTION_TYPE = 39;
  public int JJTCOLLECTION_DCL = 40;
  public int JJTELEMENT_LIST = 41;
  public int JJTELEMENT_LIST1 = 42;
  public int JJTFUNCS_DCL = 43;
  public int JJTFUNC_DCL = 44;
  public int JJTRET = 45;
  public int JJTFORMAL_PARAMETERS = 46;
  public int JJTFORMAL_PARAMETER_LIST = 47;
  public int JJTFORMAL_PARAMETER_LIST1 = 48;
  public int JJTFORMAL_PARAMETER = 49;
  public int JJTTYPE = 50;
  public int JJTOBJECT_TYPES = 51;
  public int JJTGRAPH_ELEMENT_TYPES = 52;
  public int JJTSTMT = 53;
  public int JJTSTMT1 = 54;
  public int JJTASSIGNMENT = 55;
  public int JJTLOOP = 56;
  public int JJTWHILE_STATEMENT = 57;
  public int JJTFOR_STATEMENT = 58;
  public int JJTFOREACH_STATEMENT = 59;
  public int JJTIF_STATEMENT = 60;
  public int JJTEMPTY = 61;


  public String[] jjtNodeName = {
    "ONE_LINE",
    "PROG",
    "MAIN",
    "BLOCK",
    "BLOCK_CONTENT",
    "DCL",
    "IDENTIFIER",
    "INITIALIZATION",
    "ADT",
    "GRAPH_TYPE",
    "GRAPH_DCL",
    "GRAPH_DCL1",
    "GRAPH_VERTEX_DCL",
    "GRAPH_VERTEX_DCL1",
    "VERTEX_LIST",
    "VERTEX_LIST1",
    "WEIGHT",
    "EXPR",
    "A",
    "AND_EXPR",
    "B",
    "EQUAL_EXPR",
    "EQUAL_EXPR1",
    "REL_EXPR",
    "REL_EXPR1",
    "ARITH_EXPR",
    "C",
    "TERM",
    "D",
    "NEG_EXPR",
    "ATOMIC_EXPR",
    "VALUE",
    "VALUE1",
    "FUNCTION_CALL1",
    "FUNCTION_CALL",
    "ACTUAL_PARAMETERS",
    "ACTUAL_PARAMETER_LIST",
    "ACTUAL_PARAMETER_LIST1",
    "SIMPLE_TYPES",
    "COLLECTION_TYPE",
    "COLLECTION_DCL",
    "ELEMENT_LIST",
    "ELEMENT_LIST1",
    "FUNCS_DCL",
    "FUNC_DCL",
    "RET",
    "FORMAL_PARAMETERS",
    "FORMAL_PARAMETER_LIST",
    "FORMAL_PARAMETER_LIST1",
    "FORMAL_PARAMETER",
    "TYPE",
    "OBJECT_TYPES",
    "GRAPH_ELEMENT_TYPES",
    "STMT",
    "STMT1",
    "ASSIGNMENT",
    "LOOP",
    "WHILE_STATEMENT",
    "FOR_STATEMENT",
    "FOREACH_STATEMENT",
    "IF_STATEMENT",
    "EMPTY",
  };
}
/* JavaCC - OriginalChecksum=0243e9b89a5ccd958cfd56731a90387a (do not edit this line) */
