/* Generated By:JJTree: Do not edit this line. ASTATTRIBUTES_DCL.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTATTRIBUTES_DCL extends SimpleNode {
  public ASTATTRIBUTES_DCL(int id) {
    super(id);
  }

  public ASTATTRIBUTES_DCL(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0602f64b2f13f8ef9c100e691d28d32f (do not edit this line) */
