/* Generated By:JJTree: Do not edit this line. ASTADD_SUB.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTADD_SUB extends SimpleNode {
  public ASTADD_SUB(int id) {
    super(id);
  }

  public ASTADD_SUB(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=73e6f05a4a6d7e35a846d8aef9a992b3 (do not edit this line) */
