/* Generated By:JJTree: Do not edit this line. ASTATTRIBUTE_DCL.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTATTRIBUTE_DCL extends SimpleNode {
  public ASTATTRIBUTE_DCL(int id) {
    super(id);
  }

  public ASTATTRIBUTE_DCL(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f2c8aaabb8e8a7d52003421c0c4c4b5d (do not edit this line) */
