/* Generated By:JJTree: Do not edit this line. ASTACTUAL_PARAMETERS.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTACTUAL_PARAMETERS extends SimpleNode {
  public ASTACTUAL_PARAMETERS(int id) {
    super(id);
  }

  public ASTACTUAL_PARAMETERS(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=95ac20688d5d831eae8418b6e1ab2ad8 (do not edit this line) */
