/* Generated By:JJTree: Do not edit this line. ASTBOOL_VAL.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTBOOL_VAL extends SimpleNode {
  public ASTBOOL_VAL(int id) {
    super(id);
  }

  public ASTBOOL_VAL(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d8e25ab71c672f3109f5da0e778439bb (do not edit this line) */
