/* Generated By:JJTree: Do not edit this line. ASTCOLLECTION_ASSIGN.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTCOLLECTION_ASSIGN extends SimpleNode {
  public ASTCOLLECTION_ASSIGN(int id) {
    super(id);
  }

  public ASTCOLLECTION_ASSIGN(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=223f54ce90faddea34b57810306ebca1 (do not edit this line) */
