/* Generated By:JJTree: Do not edit this line. ASTCONSTANT_VAL.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTCONSTANT_VAL extends SimpleNode {
  public ASTCONSTANT_VAL(int id) {
    super(id);
  }

  public ASTCONSTANT_VAL(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a0eaa7c5ce32c863d3aa9ef02bc0483d (do not edit this line) */
