/* Generated By:JJTree: Do not edit this line. ASTCOLLECTION_ADT.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTCOLLECTION_ADT extends SimpleNode {
  public ASTCOLLECTION_ADT(int id) {
    super(id);
  }

  public ASTCOLLECTION_ADT(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=16fc1549f3adc71ff833d25e4966fde1 (do not edit this line) */
