/* Generated By:JJTree: Do not edit this line. ASTCOLLECTION_TYPE.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTCOLLECTION_TYPE extends SimpleNode {
  public ASTCOLLECTION_TYPE(int id) {
    super(id);
  }

  public ASTCOLLECTION_TYPE(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f3f7fdacd7efddb4600b42b781dbc126 (do not edit this line) */
