/* Generated By:JJTree: Do not edit this line. ASTELSE_STATEMENT.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTELSE_STATEMENT extends SimpleNode {
  public ASTELSE_STATEMENT(int id) {
    super(id);
  }

  public ASTELSE_STATEMENT(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b49771881acaf886764ee766098a52d2 (do not edit this line) */
