/* Generated By:JJTree: Do not edit this line. ASTEDGE_ATTRIBUTES.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTEDGE_ATTRIBUTES extends SimpleNode {
  public ASTEDGE_ATTRIBUTES(int id) {
    super(id);
  }

  public ASTEDGE_ATTRIBUTES(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=611935ebd0b22f9abb9349e6d08e1009 (do not edit this line) */
