/* Generated By:JJTree: Do not edit this line. ASTEQUAL_EXPR.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTEQUAL_EXPR extends SimpleNode {
  public ASTEQUAL_EXPR(int id) {
    super(id);
  }

  public ASTEQUAL_EXPR(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e28a862286506522982291481312a05f (do not edit this line) */
