/* Generated By:JJTree: Do not edit this line. ASTFORMAL_PARAMETERS.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTFORMAL_PARAMETERS extends SimpleNode {
  public ASTFORMAL_PARAMETERS(int id) {
    super(id);
  }

  public ASTFORMAL_PARAMETERS(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e19974e7c470a34d1c46a2d5c23551cb (do not edit this line) */
