/* Generated By:JJTree: Do not edit this line. ASTFOREACH_STATEMENT.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTFOREACH_STATEMENT extends SimpleNode {
  public ASTFOREACH_STATEMENT(int id) {
    super(id);
  }

  public ASTFOREACH_STATEMENT(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b2ca31bdd2fba61e45c74501234e87ae (do not edit this line) */
