/* Generated By:JJTree: Do not edit this line. ASTFUNCTION_CALL_STMT.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTFUNCTION_CALL_STMT extends SimpleNode {
  public ASTFUNCTION_CALL_STMT(int id) {
    super(id);
  }

  public ASTFUNCTION_CALL_STMT(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=291bf4af6a883170450b7ffd010fec3e (do not edit this line) */
