/* Generated By:JJTree: Do not edit this line. ASTFUNCS_DCL.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTFUNCS_DCL extends SimpleNode {
  public ASTFUNCS_DCL(int id) {
    super(id);
  }

  public ASTFUNCS_DCL(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e8ce924e7292da20267026b7f0f2afe3 (do not edit this line) */
