/* Generated By:JJTree: Do not edit this line. ASTFUNC_CALL.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTFUNC_CALL extends SimpleNode {
  public ASTFUNC_CALL(int id) {
    super(id);
  }

  public ASTFUNC_CALL(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=70c10e5d64580021d320d4bfbf0f79b0 (do not edit this line) */
