/* Generated By:JJTree: Do not edit this line. ASTFNUM_VAL.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTFNUM_VAL extends SimpleNode {
  public ASTFNUM_VAL(int id) {
    super(id);
  }

  public ASTFNUM_VAL(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a60b81293501c428962c34afd987b8cf (do not edit this line) */
