/* Generated By:JJTree: Do not edit this line. ASTFIELD_ACCESS.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTFIELD_ACCESS extends SimpleNode {
  public ASTFIELD_ACCESS(int id) {
    super(id);
  }

  public ASTFIELD_ACCESS(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6945b9555bc9112b1f765ffa7e694738 (do not edit this line) */
