/* Generated By:JJTree: Do not edit this line. ASTFUNCTION_CALL.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTFUNCTION_CALL extends SimpleNode {
  public ASTFUNCTION_CALL(int id) {
    super(id);
  }

  public ASTFUNCTION_CALL(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4bc2642e3035b45b2669afc713471da9 (do not edit this line) */
