/* Generated By:JJTree: Do not edit this line. ASTGRAPH_DCL.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTGRAPH_DCL extends SimpleNode {
  public ASTGRAPH_DCL(int id) {
    super(id);
  }

  public ASTGRAPH_DCL(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=cbd1fe3e0c3bf12819d535a172ca5136 (do not edit this line) */
