/* Generated By:JJTree: Do not edit this line. ASTGRAPH_ELEMENT_TYPES.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTGRAPH_ELEMENT_TYPES extends SimpleNode {
  public ASTGRAPH_ELEMENT_TYPES(int id) {
    super(id);
  }

  public ASTGRAPH_ELEMENT_TYPES(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2fcce8ff513e6da82dacf82ea74dc2d2 (do not edit this line) */
