/* Generated By:JJTree: Do not edit this line. ASTGRAPH_ASSIGN.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTGRAPH_ASSIGN extends SimpleNode {
  public ASTGRAPH_ASSIGN(int id) {
    super(id);
  }

  public ASTGRAPH_ASSIGN(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=beb71e31e98301765a9af7ef4d2f385c (do not edit this line) */
