/* Generated By:JJTree: Do not edit this line. ASTGRAPH_DCL_ELEMENTS.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTGRAPH_DCL_ELEMENTS extends SimpleNode {
  public ASTGRAPH_DCL_ELEMENTS(int id) {
    super(id);
  }

  public ASTGRAPH_DCL_ELEMENTS(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5756ecd8c1df3fdd71f383b67500796b (do not edit this line) */
