/* Generated By:JJTree: Do not edit this line. ASTGRAPH_VERTEX_DCL.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTGRAPH_VERTEX_DCL extends SimpleNode {
  public ASTGRAPH_VERTEX_DCL(int id) {
    super(id);
  }

  public ASTGRAPH_VERTEX_DCL(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0d38bb005babe48076a3072ff8f4af10 (do not edit this line) */
