/* Generated By:JJTree: Do not edit this line. ASTIF_STATEMENT.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTIF_STATEMENT extends SimpleNode {
  public ASTIF_STATEMENT(int id) {
    super(id);
  }

  public ASTIF_STATEMENT(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3b39e2ce1d6c1faee1d4ee675cdefd3e (do not edit this line) */
