/* Generated By:JJTree: Do not edit this line. ASTINUM_VAL.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTINUM_VAL extends SimpleNode {
  public ASTINUM_VAL(int id) {
    super(id);
  }

  public ASTINUM_VAL(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=848359a8246f45211539e1f08a40d216 (do not edit this line) */
