/* Generated By:JJTree: Do not edit this line. ASTINITIALIZATION.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTINITIALIZATION extends SimpleNode {
  public ASTINITIALIZATION(int id) {
    super(id);
  }

  public ASTINITIALIZATION(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=50f6c4e71da5b60182a0dca3b8efa2e0 (do not edit this line) */
