/* Generated By:JJTree: Do not edit this line. ASTIDENTIFIER.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTIDENTIFIER extends SimpleNode {
  public ASTIDENTIFIER(int id) {
    super(id);
  }

  public ASTIDENTIFIER(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4df2ac07718d16eca4fb72096c58a7fb (do not edit this line) */
