/* Generated By:JJTree: Do not edit this line. ASTLABEL_VAL.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTLABEL_VAL extends SimpleNode {
  public ASTLABEL_VAL(int id) {
    super(id);
  }

  public ASTLABEL_VAL(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2e7b8eed414644cda8a65fbbf38a9699 (do not edit this line) */
