/* Generated By:JJTree: Do not edit this line. ASTMAP_ELEMENT_LIST.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTMAP_ELEMENT_LIST extends SimpleNode {
  public ASTMAP_ELEMENT_LIST(int id) {
    super(id);
  }

  public ASTMAP_ELEMENT_LIST(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3f233148277d1168073b2e3ffca1fb67 (do not edit this line) */
