/* Generated By:JJTree: Do not edit this line. ASTMUL_DIV.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTMUL_DIV extends SimpleNode {
  public ASTMUL_DIV(int id) {
    super(id);
  }

  public ASTMUL_DIV(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=50a1b9fda64ba110703b254ae8566a56 (do not edit this line) */
