/* Generated By:JJTree: Do not edit this line. ASTMEMBER_FUNCTION_CALL.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTMEMBER_FUNCTION_CALL extends SimpleNode {
  public ASTMEMBER_FUNCTION_CALL(int id) {
    super(id);
  }

  public ASTMEMBER_FUNCTION_CALL(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6766fbfc88ac21fe7b51b6db408e1af6 (do not edit this line) */
