/* Generated By:JJTree: Do not edit this line. ASTMAP_ADT.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTMAP_ADT extends SimpleNode {
  public ASTMAP_ADT(int id) {
    super(id);
  }

  public ASTMAP_ADT(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b951e9984e021e5dff22a8fd3a337e54 (do not edit this line) */
