/* Generated By:JJTree: Do not edit this line. ASTMUL_DIV_MOD.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTMUL_DIV_MOD extends SimpleNode {
  public ASTMUL_DIV_MOD(int id) {
    super(id);
  }

  public ASTMUL_DIV_MOD(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e89e97dec9cd83a87be1e44aebd6d500 (do not edit this line) */
