/* Generated By:JJTree: Do not edit this line. ASTNEG_EXPR.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTNEG_EXPR extends SimpleNode {
  public ASTNEG_EXPR(int id) {
    super(id);
  }

  public ASTNEG_EXPR(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e6d4101982890ad22be7de49fc33d843 (do not edit this line) */
