/* Generated By:JJTree: Do not edit this line. ASTOBJECT_ATTRIBUTE_DCL.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTOBJECT_ATTRIBUTE_DCL extends SimpleNode {
  public ASTOBJECT_ATTRIBUTE_DCL(int id) {
    super(id);
  }

  public ASTOBJECT_ATTRIBUTE_DCL(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=934628a8c576e32c30382e4257b83799 (do not edit this line) */
