/* Generated By:JJTree: Do not edit this line. ASTOBJECT_TYPES.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTOBJECT_TYPES extends SimpleNode {
  public ASTOBJECT_TYPES(int id) {
    super(id);
  }

  public ASTOBJECT_TYPES(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=72652d718436acce059e4a678f2d39d8 (do not edit this line) */
