/* Generated By:JJTree: Do not edit this line. ASTOR_EXPR.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTOR_EXPR extends SimpleNode {
  public ASTOR_EXPR(int id) {
    super(id);
  }

  public ASTOR_EXPR(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f986209b8b6a65af776e09d0397b8047 (do not edit this line) */
