/* Generated By:JJTree: Do not edit this line. ASTRETURN_STMT.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTRETURN_STMT extends SimpleNode {
  public ASTRETURN_STMT(int id) {
    super(id);
  }

  public ASTRETURN_STMT(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bf9b46795460c3cecfd52821d71de1d6 (do not edit this line) */
