/* Generated By:JJTree: Do not edit this line. ASTRETURN_TYPE.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTRETURN_TYPE extends SimpleNode {
  public ASTRETURN_TYPE(int id) {
    super(id);
  }

  public ASTRETURN_TYPE(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5a142faa00e18055cf34bcd296f492a1 (do not edit this line) */
