/* Generated By:JJTree: Do not edit this line. ASTREL_EXPR.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTREL_EXPR extends SimpleNode {
  public ASTREL_EXPR(int id) {
    super(id);
  }

  public ASTREL_EXPR(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8b6067c3f542066a48b7ce4990abaf84 (do not edit this line) */
