/* Generated By:JJTree: Do not edit this line. ASTSIMPLE_DCL.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTSIMPLE_DCL extends SimpleNode {
  public ASTSIMPLE_DCL(int id) {
    super(id);
  }

  public ASTSIMPLE_DCL(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1b18a835b2c5d36e44f41799a842c783 (do not edit this line) */
