/* Generated By:JJTree: Do not edit this line. ASTSIMPLE_TYPES.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTSIMPLE_TYPES extends SimpleNode {
  public ASTSIMPLE_TYPES(int id) {
    super(id);
  }

  public ASTSIMPLE_TYPES(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=dd9db21122113fb94dab2c801b3a0d0f (do not edit this line) */
