/* Generated By:JJTree: Do not edit this line. ASTSIMPLE_ATTRIBUTES_DCL.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTSIMPLE_ATTRIBUTES_DCL extends SimpleNode {
  public ASTSIMPLE_ATTRIBUTES_DCL(int id) {
    super(id);
  }

  public ASTSIMPLE_ATTRIBUTES_DCL(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=081460e4816e2e7b59cbd69a0b43c4e9 (do not edit this line) */
