/* Generated By:JJTree: Do not edit this line. ASTVERTEX_ATTRIBUTES.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTVERTEX_ATTRIBUTES extends SimpleNode {
  public ASTVERTEX_ATTRIBUTES(int id) {
    super(id);
  }

  public ASTVERTEX_ATTRIBUTES(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0d0330d53be13ce412b723991f2877f4 (do not edit this line) */
