/* Generated By:JJTree: Do not edit this line. ASTVERTEX_EDGE_ATTR.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTVERTEX_EDGE_ATTR extends SimpleNode {
  public ASTVERTEX_EDGE_ATTR(int id) {
    super(id);
  }

  public ASTVERTEX_EDGE_ATTR(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8a4ec033578224bd69b854014bd72f9b (do not edit this line) */
