/* Generated By:JJTree: Do not edit this line. ASTVERTEX_LIST.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTVERTEX_LIST extends SimpleNode {
  public ASTVERTEX_LIST(int id) {
    super(id);
  }

  public ASTVERTEX_LIST(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=637ef326d3f8a6bf702f521b4e1a25d4 (do not edit this line) */
