/* Generated By:JJTree: Do not edit this line. ASTWEIGHT.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTWEIGHT extends SimpleNode {
  public ASTWEIGHT(int id) {
    super(id);
  }

  public ASTWEIGHT(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d46bf3f3779d15270bda087893d336a7 (do not edit this line) */
