/* Generated By:JJTree: Do not edit this line. ASTWHILE_STATEMENT.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Compiler.Parser.GeneratedFiles;

public
class ASTWHILE_STATEMENT extends SimpleNode {
  public ASTWHILE_STATEMENT(int id) {
    super(id);
  }

  public ASTWHILE_STATEMENT(TestParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TestParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8e7018f75384b1e9661a363cfd8c2f26 (do not edit this line) */
