/* Generated By:JavaCC: Do not edit this line. TestParserTreeConstants.java Version 6.0_1 */
package Compiler.Parser.GeneratedFiles;

public interface TestParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTSTART = 1;
  public int JJTPROG = 2;
  public int JJTFUNCS_DCL = 3;
  public int JJTVERTEX_EDGE_ATTR = 4;
  public int JJTVERTEX_ATTRIBUTES = 5;
  public int JJTEDGE_ATTRIBUTES = 6;
  public int JJTATTRIBUTE_DCL = 7;
  public int JJTOBJECT_TYPE = 8;
  public int JJTSIMPLE_DCL = 9;
  public int JJTSIMPLE_TYPES = 10;
  public int JJTIDENTIFIER = 11;
  public int JJTMAP = 12;
  public int JJTCOLLECTION_TYPE = 13;
  public int JJTGRAPH_ELEMENT_TYPES = 14;
  public int JJTOR_EXPR = 15;
  public int JJTAND_EXPR = 16;
  public int JJTEQUAL_EXPR = 17;
  public int JJTREL_EXPR = 18;
  public int JJTADD_SUB = 19;
  public int JJTMUL_DIV = 20;
  public int JJTNEG_EXPR = 21;
  public int JJTINUM_VAL = 22;
  public int JJTFNUM_VAL = 23;
  public int JJTBOOL_VAL = 24;
  public int JJTCONSTANT_VAL = 25;
  public int JJTVARIABLE = 26;
  public int JJTFUNCTION_CALL = 27;
  public int JJTFIELD_ACCESS = 28;
  public int JJTACTUAL_PARAMETERS = 29;
  public int JJTMAIN = 30;
  public int JJTBLOCK = 31;
  public int JJTGRAPH_ELEMENT_DCL = 32;
  public int JJTCREATE = 33;
  public int JJTGRAPH_DCL = 34;
  public int JJTGRAPH_TYPE = 35;
  public int JJTGRAPH_ASSIGN = 36;
  public int JJTGRAPH_DCL_ELEMENTS = 37;
  public int JJTGRAPH_VERTEX_DCL = 38;
  public int JJTVERTEX_LIST = 39;
  public int JJTVERTEX = 40;
  public int JJTWEIGHT = 41;
  public int JJTASSIGN = 42;
  public int JJTFUNCTION_CALL_STMT = 43;
  public int JJTWHILE_STATEMENT = 44;
  public int JJTFOR_STATEMENT = 45;
  public int JJTFOREACH_STATEMENT = 46;
  public int JJTIF_STATEMENT = 47;
  public int JJTELSE_STATEMENT = 48;
  public int JJTRETURN_STMT = 49;
  public int JJTCOLLECTION_ADT = 50;
  public int JJTELEMENT_LIST = 51;
  public int JJTFUNC_DCL = 52;
  public int JJTRETURN_TYPE = 53;
  public int JJTFORMAL_PARAMETERS = 54;
  public int JJTFORMAL_PARAMETER = 55;


  public String[] jjtNodeName = {
    "void",
    "START",
    "PROG",
    "FUNCS_DCL",
    "VERTEX_EDGE_ATTR",
    "VERTEX_ATTRIBUTES",
    "EDGE_ATTRIBUTES",
    "ATTRIBUTE_DCL",
    "OBJECT_TYPE",
    "SIMPLE_DCL",
    "SIMPLE_TYPES",
    "IDENTIFIER",
    "MAP",
    "COLLECTION_TYPE",
    "GRAPH_ELEMENT_TYPES",
    "OR_EXPR",
    "AND_EXPR",
    "EQUAL_EXPR",
    "REL_EXPR",
    "ADD_SUB",
    "MUL_DIV",
    "NEG_EXPR",
    "INUM_VAL",
    "FNUM_VAL",
    "BOOL_VAL",
    "CONSTANT_VAL",
    "VARIABLE",
    "FUNCTION_CALL",
    "FIELD_ACCESS",
    "ACTUAL_PARAMETERS",
    "MAIN",
    "BLOCK",
    "GRAPH_ELEMENT_DCL",
    "CREATE",
    "GRAPH_DCL",
    "GRAPH_TYPE",
    "GRAPH_ASSIGN",
    "GRAPH_DCL_ELEMENTS",
    "GRAPH_VERTEX_DCL",
    "VERTEX_LIST",
    "VERTEX",
    "WEIGHT",
    "ASSIGN",
    "FUNCTION_CALL_STMT",
    "WHILE_STATEMENT",
    "FOR_STATEMENT",
    "FOREACH_STATEMENT",
    "IF_STATEMENT",
    "ELSE_STATEMENT",
    "RETURN_STMT",
    "COLLECTION_ADT",
    "ELEMENT_LIST",
    "FUNC_DCL",
    "RETURN_TYPE",
    "FORMAL_PARAMETERS",
    "FORMAL_PARAMETER",
  };
}
/* JavaCC - OriginalChecksum=71e56c181762d869e248d60cf8a30fa9 (do not edit this line) */
