/* Generated By:JavaCC: Do not edit this line. TestParserTreeConstants.java Version 6.0_1 */
package Compiler.Parser.GeneratedFiles;

public interface TestParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTSTART = 1;
  public int JJTPROG = 2;
  public int JJTVERTEX_ATTRIBUTES = 3;
  public int JJTEDGE_ATTRIBUTES = 4;
  public int JJTATTRIBUTE_DCL = 5;
  public int JJTASSIGN = 6;
  public int JJTOBJECT_TYPE = 7;
  public int JJTSIMPLE_TYPES = 8;
  public int JJTIDENTIFIER = 9;
  public int JJTOBJECT_TYPES = 10;
  public int JJTCOLLECTION_TYPE = 11;
  public int JJTOR_EXPR = 12;
  public int JJTAND_EXPR = 13;
  public int JJTEQUAL_EXPR = 14;
  public int JJTREL_EXPR = 15;
  public int JJTADD_SUB = 16;
  public int JJTMUL_DIV = 17;
  public int JJTNEG_EXPR = 18;
  public int JJTVALUE = 19;
  public int JJTMEMBER_FUNCTION_CALL = 20;
  public int JJTACTUAL_PARAMETERS = 21;
  public int JJTBLOCK = 22;
  public int JJTCREATE = 23;
  public int JJTGRAPH_TYPE = 24;
  public int JJTGRAPH_DCL = 25;
  public int JJTGRAPH_VERTEX_DCL = 26;
  public int JJTVERTEX_LIST = 27;
  public int JJTVERTEX = 28;
  public int JJTWEIGHT = 29;
  public int JJTSTMT = 30;
  public int JJTFUNC_CALL = 31;
  public int JJTLOOP = 32;
  public int JJTWHILE_STATEMENT = 33;
  public int JJTFOR_STATEMENT = 34;
  public int JJTINTEGER_VALUE = 35;
  public int JJTFOREACH_STATEMENT = 36;
  public int JJTIF_STATEMENT = 37;
  public int JJTELSE_STATEMENT = 38;
  public int JJTRETURN_STMT = 39;
  public int JJTCOLLECTION_ADT = 40;
  public int JJTCOLLECTION_DCL = 41;
  public int JJTELEMENT_LIST = 42;
  public int JJTFUNCS_DCL = 43;
  public int JJTFUNC_DCL = 44;
  public int JJTFORMAL_PARAMETERS = 45;
  public int JJTFORMAL_PARAMETER = 46;


  public String[] jjtNodeName = {
    "void",
    "START",
    "PROG",
    "VERTEX_ATTRIBUTES",
    "EDGE_ATTRIBUTES",
    "ATTRIBUTE_DCL",
    "ASSIGN",
    "OBJECT_TYPE",
    "SIMPLE_TYPES",
    "IDENTIFIER",
    "OBJECT_TYPES",
    "COLLECTION_TYPE",
    "OR_EXPR",
    "AND_EXPR",
    "EQUAL_EXPR",
    "REL_EXPR",
    "ADD_SUB",
    "MUL_DIV",
    "NEG_EXPR",
    "VALUE",
    "MEMBER_FUNCTION_CALL",
    "ACTUAL_PARAMETERS",
    "BLOCK",
    "CREATE",
    "GRAPH_TYPE",
    "GRAPH_DCL",
    "GRAPH_VERTEX_DCL",
    "VERTEX_LIST",
    "VERTEX",
    "WEIGHT",
    "STMT",
    "FUNC_CALL",
    "LOOP",
    "WHILE_STATEMENT",
    "FOR_STATEMENT",
    "INTEGER_VALUE",
    "FOREACH_STATEMENT",
    "IF_STATEMENT",
    "ELSE_STATEMENT",
    "RETURN_STMT",
    "COLLECTION_ADT",
    "COLLECTION_DCL",
    "ELEMENT_LIST",
    "FUNCS_DCL",
    "FUNC_DCL",
    "FORMAL_PARAMETERS",
    "FORMAL_PARAMETER",
  };
}
/* JavaCC - OriginalChecksum=325c55825f38f24ecba4db36e2c6663e (do not edit this line) */
