/* Generated By:JavaCC: Do not edit this line. TestParserTreeConstants.java Version 6.0_1 */
package Compiler.Parser.GeneratedFiles;

public interface TestParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTSTART = 1;
  public int JJTPROG = 2;
  public int JJTFUNCS_DCL = 3;
  public int JJTVERTEX_EDGE_ATTR = 4;
  public int JJTVERTEX_ATTRIBUTES = 5;
  public int JJTEDGE_ATTRIBUTES = 6;
  public int JJTSIMPLE_ATTRIBUTES_DCL = 7;
  public int JJTOBJECT_ATTRIBUTE_DCL = 8;
  public int JJTSIMPLE_DCL = 9;
  public int JJTSIMPLE_TYPES = 10;
  public int JJTIDENTIFIER = 11;
  public int JJTMAP = 12;
  public int JJTCOLLECTION_TYPE = 13;
  public int JJTOR_EXPR = 14;
  public int JJTAND_EXPR = 15;
  public int JJTEQUAL_EXPR = 16;
  public int JJTREL_EXPR = 17;
  public int JJTADD_SUB = 18;
  public int JJTMUL_DIV_MOD = 19;
  public int JJTNEG_EXPR = 20;
  public int JJTINUM_VAL = 21;
  public int JJTFNUM_VAL = 22;
  public int JJTBOOL_VAL = 23;
  public int JJTCONSTANT_VAL = 24;
  public int JJTCOLOR_VAL = 25;
  public int JJTLABEL_VAL = 26;
  public int JJTVARIABLE = 27;
  public int JJTFUNCTION_CALL = 28;
  public int JJTFIELD_ACCESS = 29;
  public int JJTACTUAL_PARAMETERS = 30;
  public int JJTMAIN = 31;
  public int JJTBLOCK = 32;
  public int JJTGRAPH_DCL = 33;
  public int JJTGRAPH_TYPE = 34;
  public int JJTGRAPH_ASSIGN = 35;
  public int JJTGRAPH_DCL_ELEMENTS = 36;
  public int JJTGRAPH_VERTEX_DCL = 37;
  public int JJTVERTEX_LIST = 38;
  public int JJTVERTEX = 39;
  public int JJTWEIGHT = 40;
  public int JJTASSIGN = 41;
  public int JJTFUNCTION_CALL_STMT = 42;
  public int JJTWHILE_STATEMENT = 43;
  public int JJTFOR_STATEMENT = 44;
  public int JJTFOREACH_STATEMENT = 45;
  public int JJTIF_STATEMENT = 46;
  public int JJTELSE_STATEMENT = 47;
  public int JJTRETURN_STMT = 48;
  public int JJTCOLLECTION_ADT = 49;
  public int JJTCOLLECTION_ASSIGN = 50;
  public int JJTELEMENT_LIST = 51;
  public int JJTMAP_ADT = 52;
  public int JJTMAP_ASSIGN = 53;
  public int JJTMAP_ELEMENT_LIST = 54;
  public int JJTKEY_VALUE_PAIR = 55;
  public int JJTFUNC_DCL = 56;
  public int JJTRETURN_TYPE = 57;
  public int JJTFORMAL_PARAMETERS = 58;
  public int JJTFORMAL_PARAMETER = 59;


  public String[] jjtNodeName = {
    "void",
    "START",
    "PROG",
    "FUNCS_DCL",
    "VERTEX_EDGE_ATTR",
    "VERTEX_ATTRIBUTES",
    "EDGE_ATTRIBUTES",
    "SIMPLE_ATTRIBUTES_DCL",
    "OBJECT_ATTRIBUTE_DCL",
    "SIMPLE_DCL",
    "SIMPLE_TYPES",
    "IDENTIFIER",
    "MAP",
    "COLLECTION_TYPE",
    "OR_EXPR",
    "AND_EXPR",
    "EQUAL_EXPR",
    "REL_EXPR",
    "ADD_SUB",
    "MUL_DIV_MOD",
    "NEG_EXPR",
    "INUM_VAL",
    "FNUM_VAL",
    "BOOL_VAL",
    "CONSTANT_VAL",
    "COLOR_VAL",
    "LABEL_VAL",
    "VARIABLE",
    "FUNCTION_CALL",
    "FIELD_ACCESS",
    "ACTUAL_PARAMETERS",
    "MAIN",
    "BLOCK",
    "GRAPH_DCL",
    "GRAPH_TYPE",
    "GRAPH_ASSIGN",
    "GRAPH_DCL_ELEMENTS",
    "GRAPH_VERTEX_DCL",
    "VERTEX_LIST",
    "VERTEX",
    "WEIGHT",
    "ASSIGN",
    "FUNCTION_CALL_STMT",
    "WHILE_STATEMENT",
    "FOR_STATEMENT",
    "FOREACH_STATEMENT",
    "IF_STATEMENT",
    "ELSE_STATEMENT",
    "RETURN_STMT",
    "COLLECTION_ADT",
    "COLLECTION_ASSIGN",
    "ELEMENT_LIST",
    "MAP_ADT",
    "MAP_ASSIGN",
    "MAP_ELEMENT_LIST",
    "KEY_VALUE_PAIR",
    "FUNC_DCL",
    "RETURN_TYPE",
    "FORMAL_PARAMETERS",
    "FORMAL_PARAMETER",
  };
}
/* JavaCC - OriginalChecksum=1e37b9a2212e7cf6d90b015a89880813 (do not edit this line) */
