/* Generated By:JavaCC: Do not edit this line. TestParserVisitor.java Version 6.0_1 */
package Compiler.Parser.GeneratedFiles;

public interface TestParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTSTART node, Object data);
  public Object visit(ASTPROG node, Object data);
  public Object visit(ASTVERTEX_ATTRIBUTES node, Object data);
  public Object visit(ASTEDGE_ATTRIBUTES node, Object data);
  public Object visit(ASTATTRIBUTE_DCL node, Object data);
  public Object visit(ASTASSIGN node, Object data);
  public Object visit(ASTOBJECT_TYPE node, Object data);
  public Object visit(ASTSIMPLE_TYPES node, Object data);
  public Object visit(ASTIDENTIFIER node, Object data);
  public Object visit(ASTOBJECT_TYPES node, Object data);
  public Object visit(ASTCOLLECTION_TYPE node, Object data);
  public Object visit(ASTOR_EXPR node, Object data);
  public Object visit(ASTAND_EXPR node, Object data);
  public Object visit(ASTEQUAL_EXPR node, Object data);
  public Object visit(ASTREL_EXPR node, Object data);
  public Object visit(ASTADD_SUB node, Object data);
  public Object visit(ASTMUL_DIV node, Object data);
  public Object visit(ASTNEG_EXPR node, Object data);
  public Object visit(ASTVALUE node, Object data);
  public Object visit(ASTMEMBER_FUNCTION_CALL node, Object data);
  public Object visit(ASTACTUAL_PARAMETERS node, Object data);
  public Object visit(ASTBLOCK node, Object data);
  public Object visit(ASTCREATE node, Object data);
  public Object visit(ASTGRAPH_TYPE node, Object data);
  public Object visit(ASTGRAPH_DCL node, Object data);
  public Object visit(ASTGRAPH_VERTEX_DCL node, Object data);
  public Object visit(ASTVERTEX_LIST node, Object data);
  public Object visit(ASTVERTEX node, Object data);
  public Object visit(ASTWEIGHT node, Object data);
  public Object visit(ASTSTMT node, Object data);
  public Object visit(ASTFUNC_CALL node, Object data);
  public Object visit(ASTLOOP node, Object data);
  public Object visit(ASTWHILE_STATEMENT node, Object data);
  public Object visit(ASTFOR_STATEMENT node, Object data);
  public Object visit(ASTINTEGER_VALUE node, Object data);
  public Object visit(ASTFOREACH_STATEMENT node, Object data);
  public Object visit(ASTIF_STATEMENT node, Object data);
  public Object visit(ASTELSE_STATEMENT node, Object data);
  public Object visit(ASTRETURN_STMT node, Object data);
  public Object visit(ASTCOLLECTION_ADT node, Object data);
  public Object visit(ASTELEMENT_LIST node, Object data);
  public Object visit(ASTFUNCS_DCL node, Object data);
  public Object visit(ASTFUNC_DCL node, Object data);
  public Object visit(ASTFORMAL_PARAMETERS node, Object data);
  public Object visit(ASTFORMAL_PARAMETER node, Object data);
}
/* JavaCC - OriginalChecksum=e98bb79036f946d46d662a6e792fde26 (do not edit this line) */
